---
title: "Hot Deck Imputation"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/UGA/Courses/Fall 2023/MIST 7635 Machine Learning Bus Analytics/Group Projects")
library(caret)
library(tidyverse)
library(VIM)
library(ROSE)
```

## Load data
```{r}
# Load the data
dat <- read.csv("Data/wcgs.csv")
```

```{r}
# Imputing cholesterol within domain
dat_imp <- hotdeck(
dat,
variable = "chol",
domain_var = c("smoke","dibpat"),
ord_var = c("age","bmi"))

# examine the imputed cholesterol value  
dat_imp[is.na(dat$chol),"chol"]

# Imputing arcus within domain
dat_imp <- hotdeck(
dat_imp,
variable = "arcus",
domain_var = c("smoke","dibpat"),
ord_var = c("age","chol"))

# examine the imputed arcus value  
dat_imp[is.na(dat$arcus),"arcus"]

```

#### Split data
```{r}
set.seed(123)
# create train/test split
idx = createDataPartition(dat_imp$chd69, p=0.75, list=F)
train.chd69 = dat_imp[idx,]
test.chd69 = dat_imp[-idx,]

write.csv(train.chd69, "Data/train.chd69.csv", row.names = F)
write.csv(test.chd69, "Data/test.chd69.csv", row.names = F)
```

#### Descriptive analysis
```{r}
table <-
  dat %>% 
  select(age,bmi,lnsbp,dbp,chol,dibpat,smoke,arcus,chd69) %>% 
  tbl_summary(
    by = chd69, 
    missing = "no" # don't list missing data separately
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p() %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels()

table
```
